apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello-service
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: hello:local
          env:
            - name: SPRING_APPLICATION_NAME
              value: "hello"
            - name: SERVER_PORT
              value: "8080"
            - name: CLIENT_APP
              value: "hello2-service:8080"
          imagePullPolicy: Never
          ports:
            - containerPort: 8080


#kubectl exec podName -- printenv | grep SERVICE

     # - name: MY_POD_IP
     #   valueFrom:
     #     fieldRef:
     #       fieldPath: status.podIP