apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello-service
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 2
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: hello:local
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP #kubernate pod icin network namespace(NM) ve sanal network interface (VNI) olusturur olusturur(pod'un NM'i olur), bu NM, VNI ile node'un fiziksel network interface'i ile pod'u  bağlar
              valueFrom:      #kubernate'in bu virtual network interface'e atadigi ip podIp oluyor
                fieldRef:     #Pod icerisinde kosan container Pod'un network namespace'ini kullanir()
                  fieldPath: status.podIP
                              #container cephesinden baktigimizda Pod bir fiziksel makinedir ve bir adet network interface'i vardir
                              #podIp static degil degisebilir
            - name: SPRING_APPLICATION_NAME
              value: "hello"
            - name: SERVER_PORT
              value: "8080"
            - name: CLIENT_APP
              value: "hello2-service:8080"
          imagePullPolicy: Never
          #imagePullSecrets: dockerhub-secret docker-hub'dan indirecekse(docker-secret kubernate secrets kısmında tanimlaniyor)
          ports:
            - containerPort: 8080 #uygulamanin iceride kullandigi port