apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: hello:local
          env:
            - name: SPRING_APPLICATION_NAME
              value: "Hello"
            - name: SERVER_PORT
              value: "8080"
          imagePullPolicy: Never
          ports:
            - containerPort: 8080