apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello2-deployment
  labels:
    app: hello2-service
spec:
  selector:
    matchLabels:
      app: hello2
  template:
    metadata:
      labels:
        app: hello2
    spec:
      containers:
        - name: hello
          image: hello:local
          env:
            - name: SPRING_APPLICATION_NAME
              value: "hello2"
            - name: SERVER_PORT
              value: "8080"
            - name: CLIENT_APP
              value: "hello-service:8080"
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
#kubectl apply -f svc-hello.yml