apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000 # 30000-32767, Optional field

#kubectl get pods -o wide --> IP:8080'den erisebilirsin
#kubectl apply -f svc-hello.yml
#kubectl get services --> localhost:30000'den erisebilirsin  localhost --> nodeIĞ