apiVersion: v1
kind: Service
metadata:
  name: hello2-service
spec:
  type: NodePort
  selector:
    app: hello2
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001 # 30000-32767, Optional field