spring:
  h2:
    console:
      enabled: true #http://localhost:8080/h2-console --> jdbc url -> jdbc:h2:mem:testdb
  application:
    name: hello
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      naming: #upper case table name
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #create table
    defer-datasource-initialization: true

server:
   port: 8080

client.app : "http://hello:8080"
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
#logging:
#  level:
#    reactor.netty: trace