apiVersion: v1
kind: Pod
metadata:
        creationTimestamp: null
        labels:
                run: aomif-pod
        name: myapp4
spec:
        containers:
                - image: localhost:32000/aomif-maven
                  name: aomif-maven
                  imagePullPolicy: IfNotPresent
                  resources: {}
        dnsPolicy: ClusterFirst
        restartPolicy: Always