spring.application.name: "eureka"
server:
  port: 8761
eureka:
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: true
    fetchRegistry: false

logging:
  level:
    root: info